- hosts: servers
  become: true
  tasks:
    - name: Copy hosts to /etc/
      ansible.builtin.copy:
        src: ./hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'