---
- hosts: servers
  become: true
  tasks:
    - name: "Install httpd"
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int > 8
    - name: "Install apache"
      ansible.builtin.apt:
        name: apache
        state: present
      when: ansible_distribution == "Debian"
...