- hosts: all
  become: true
  tasks:
    - name: Copy sudoers to /etc/
      ansible.builtin.copy:
        src: ./files/sudoers
        dest: /etc/sudoers
        owner: root
        group: root
        mode: '0440'