---
- hosts: servers
  become: true
  tasks:
    - name: "Install packages"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      with_items:
        - net-tools
        - nfs-utils
        - nmap
...